[project]
name = "tr-api-client"
version = "0.1.0"
description = "Proofpoint Threat Protection API Client"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dateutil>=2.8.0",
    "requests>=2.25.0",
]
